[workspace]
members = ["shironeko"]
resolver = "2"

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
windows = "0.58.0"
anyhow = "1.0.81"
ilhook = "2.1.0"
lazy_static = "1.4.0"
libloading = "0.8.3"
